### ISSUE TITLE
Rect of NSString

### ISSUE THREAD

**Issue by haithngnbak** [raffael/RMBlurredView#2]
Hello raffael,
Could you help me calculate Rect of NSString in Mac OS X ?
I see your screenshot display the bubble chat so nice with width and height fix, please show me how to calculate this.
Thanks,

**Comment by raffael** [comment]
Not sure what you mean, but you might wanna have a look at [NSView setAutoresizingMask:]; ?

**Comment by haithngnbak** [comment]
No no,
I want to calculate the Rect (witdh and height) of the string in OS X Apps
In iOS, it's easy to do ([string sizeWithAttributes:];) but in the OS X it's difficult to get the size of the string.
Could you show me the code that you used to calculate size of the bubble in your screenshot ?
Thanks,

**Comment by raffael** [comment]
Ah, sorry about that, I got it now.
Calculating the size of string in Cocoa is easy, you just need to know the attributes, as in iOS.
Check out for example: http://stackoverflow.com/questions/3429671/how-to-get-the-width-of-an-nsstring

However, in this case I’m using a WebView to visualize the bubbles. HTML + CSS is doing its best to properly size the bubbles!

**Comment by haithngnbak** [comment]
Thanks you very much, raffael.
