### ISSUE TITLE
Blurring the title bar

### ISSUE THREAD

**Issue by xMythicx** [raffael/RMBlurredView#3]
Hello Raffael,

Thanks so much for a wonderful little view. My apologies if this question has been answered somewhere else. I know this is probably not the appropriate place for this question although I could not find a solution anywhere.  Could you please tell my how to blur the title bar of an OSX window like the picture shown below using RMBlurredView? I have looked everywhere for an example.  Does this effect require the use of private apis? Any help would be much appreciated. Thanks so much!

![bildschirmfoto_2013-10-21_um_00_02_14](https://f.cloud.github.com/assets/322819/2341043/d00b4850-a4cf-11e3-946e-af65400dfe73.png)

**Comment by raffael** [comment]
No worries,
it’s a little bit tricky: To accomplish this effect, I’ve been using a subclass of the INAppStoreWindow and stretched the title bar across the entire window. Then, all of the window’s contentView subviews are appended to the titlebar. Next, the traffic lights are set to be layer backed (setWantsLayer:YES) and z-ordered on top of all other views.
The blurred view then is simply a RMBlurredView which is positioned above the webview, and below the traffic lights.

Hope this helps!
