### ISSUE TITLE
Make the whole window into a blurred view

### ISSUE THREAD

**Issue by holgersindbaek** [raffael/RMBlurredView#8]
I have a small calculator application and I would like the whole calculator window to be an RMBlurredView so it  blends with the background of whatever is on the desktop. How would you go about this?

![screen shot 2014-11-07 at 12 28 36](https://cloud.githubusercontent.com/assets/698979/4957346/8f5e38f8-66a3-11e4-85b5-54592a7238c2.png)

**Comment by raffael** [comment]
As mentioned in our twitter discussion, this is not possible with RMBlurredView, since this NSView subclass only blurs what's behind the view in the same NSWindow instance.

Use NSVisualEffectView on OS X 10.10 to achieve the desired behavior.
